### ISSUE TITLE
Anticheat won't work

### ISSUE THREAD

**Issue by WijZijn2Gamers** [ataranlen/civcraft#92]
I've installed the forge forge-1.11.2-13.20.0.2216-installer-win.exe and the CivCraftAC-2.0 anticheat from the website link: https://www.minetexas.com/minecraft-server-forum/showthread.php?tid=120

but when it's installed it seems like the anticheat won't load, can you please take a look at it, it says that i'm not validated by the anticheat

**Comment by ataranlen** [comment]
I'm aware that there are issues getting anti-cheat to work with Civcraft. As we do not have access to the source of CivCraftAC, it is a very difficult thing to fix.

**Comment by YourCoal** [comment]
I began fixing it a week ago, but didn't get to it today. I have decompiled it and it is available here:
https://github.com/YourCoal/CivCraft-AntiCheat-1.10.2 (CAUTION: STILL BUGGY)

As the title suggests, it is only 1.10.2 and since you run 1.11/1.11.2, you need to download the Universal Jar from https://files.minecraftforge.net/ to find the errors and fix them yourself.

**Comment by WijZijn2Gamers** [comment]
Tank you for helpinog me out.

Op 28 feb. 2017 04:40 schreef "Your Coal" <notifications@github.com>:

**Comment by TwilightVanish** [comment]
Not the best idea... releasing the source code publicly. I've now made a make shift program that will verify me no matter what I am running. Basically making the whole anticheat thing useless.

Part of the protection was not having access to the code.

I mean.. i know you can figure it out... but keeping people too lazy to do it was a good part of the protection

**Comment by ataranlen** [comment]
Anti-Cheat development has been discontinued. All code relating to its use will be removed soon.
